# Spring boot application
spring:
  application:
    name: sika-code-demo
  profiles:
    active: develop
    # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service

  batch:
    job:
      # 禁止Spring Batch自动执行,既需要用户触发才能执行
      enabled: false
      names: parentjob
    # spring batch相关表前缀, 默认为 batch_
    table-prefix: BATCH_



tlog:
  id-generator: com.sika.code.core.log.config.TraceIdGenerator
  enable-invoke-time-print: true
  pattern: '[$preApp][$preIp][$spanId][$traceId]'


liteflow:
  rule-source: config/flow.el.xml
  #-----------------以下非必须-----------------
  #liteflow是否开启，默认为true
  enable: true
  #liteflow的banner是否开启，默认为true
  print-banner: false
  #zkNode的节点，只有使用zk作为配置源的时候才起作用
  zk-node: /lite-flow/flow
  #slot的数量，默认值为1024
  slot-size: 1024
  #异步线程最长的等待时间秒(只用于when)，默认值为15
  when-max-wait-seconds: 15
  #异步线程池最大线程数，默认为16
  when-max-workers: 16
  #异步线程池等待队列数，默认为512
  when-queue-limit: 512
  #是否在启动的时候就解析规则，默认为true
  parse-on-start: false
  #全局重试次数，默认为0
  retry-count: 0
  #是否支持不同类型的加载方式混用，默认为false
  support-multiple-type: false
  #是否开启监控log打印，默认值为false
  monitor:
    enable-log: false
    #监控队列存储大小，默认值为200
    queue-limit: 300
    #监控一开始延迟多少执行，默认值为300000毫秒，也就是5分钟
    delay: 10000
    #监控日志打印每过多少时间执行一次，默认值为300000毫秒，也就是5分钟
    period: 10000

## =====================switch必须为true=============================
## jdbc开关key---sika.code.jdbc.switch

sika:
  code:
    jdbc:
      fire: true
    redis:
      fire: true
    log:
      controller:
        fire: true
      sql:
        fire: false
## =====================switch必须为true=============================
## ==========================开关配置=====================================

mybatis:
  mapper-locations: classpath*:mapper/*.xml
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl